### PR TITLE
sample application for jwt-Authentication

### LINKED ISSUE #34: [feature]: Creating Sample Java Application using JWT Token
Knowing how time based tokens like jwt and sessions work . 
And creating sample java application using jwt token authentication can be a good first issue!

### PR DESCRIPTION
**Pull request by Kshitiz-Mhto**
# Pull Request Template

## Description

Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.

Fixes keploy/keploy#424   (issue)

## Type of change

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

## Additional Context (Please include any Screenshots/gifs if relevant)

>i am going to ..

...

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules
- [x] I have checked my code and corrected any misspellings
- [ ] I have tagged the reviewers in a comment below incase my pull request is ready for a review
- [ ] I have signed the commit message to agree to Developer Certificate of Origin (DCO) (to certify that you wrote or otherwise have the right to submit your contribution to the project.) by adding "--signoff" to my git commit command.

### CODE REVIEW

**Comment by Sonichigo** [comment]
@Kshitiz-Mhto Please sign the DCO! 
```
To add your Signed-off-by line to every commit in this branch:

In your local branch, run: git rebase HEAD~1 --signoff
Force push your changes to overwrite the branch: git push --force-with-lease origin jwtsample

```

**Comment by Sonichigo** [comment]
@gouravkrosx can you review it please ?

**Comment by gouravkrosx** [comment]
@Kshitiz-Mhto Can you restructure the samples-java repo like [this](https://github.com/keploy/samples-java/pull/42)? And also add screenshots just like in [this](https://github.com/keploy/samples-java/pull/42).

**Comment by gouravkrosx** [comment]
closing due to inactivity.

**Pull request closed without merging**
