### PR TITLE
feat: add user-manager application which use springboot+mongodb

### PR DESCRIPTION
**Pull request by IllTamer**
# Pull Request Template

## Description

Closes: https://github.com/keploy/keploy/issues/913

The [README.md](https://github.com/keploy/samples-java/pull/55/files#diff-62a07aa720c3b5ed8806a971df294f4cc79272fbf464a020cf3446936246ca10) content is as follows (**RESTful api calling part**):

<hr>

#### Generate testcases

To generate testcases we just need to **make some API calls.** You can use [Postman](https://www.postman.com/), [Hoppscotch](https://hoppscotch.io/), or simply `curl`

1. Make a user entry

```bash
curl --location --request POST 'http://localhost:8081/api/user' \
--header 'Content-Type: application/json' \
--data-raw '{
    "id": 1,
    "name": "Dan",
    "age": "23",
    "birthday": "2000-1-1"
}'
```

this will return the response or an entry.

```
{"id":1,"name":"Dan","age":23,"birthday":"2000-1-1"}
```

2. Fetch recorded info about users

```bash
curl --location --request GET 'http://localhost:8081/api/user/1'
```

or by querying through the browser `http://localhost:8081/api/user/1`

3. Update user record

```bash
curl -X PUT -H "Content-Type: application/json" \
-d '{
    "id": 1,
    "name": "Update DAN",
    "age": "22",
    "birthday": "2001-2-2"
}' \
'http://localhost:8081/api/user/1'
```

this will return the response or an entry.

```
{"id":1,"name":"Update DAN","age":22,"birthday":"2001-2-2"}
```

4. Delete user record

```bash
curl -X DELETE 'http://localhost:8081/api/user/1'
```

Now both these API calls were captured as **editable** testcases and written to `keploy/test` folder. The keploy directory would also have `mock.yml` file.

Now, let's see the magic! 🪄💫

<hr>

## Type of change

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## How Has This Been Tested?

By keploy

...

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [x] Any dependent changes have been merged and published in downstream modules
- [x] I have checked my code and corrected any misspellings
- [x] I have tagged the reviewers in a comment below incase my pull request is ready for a review
- [x] I have signed the commit message to agree to Developer Certificate of Origin (DCO) (to certify that you wrote or otherwise have the right to submit your contribution to the project.) by adding "--signoff" to my git commit command.

### CODE REVIEW

**Comment by Shashwat79802** [comment]
The app works fine. Please add the examples of how to make a GET, PUT and DELETE request readme.

**Comment by IllTamer** [comment]
> The app works fine. Please add the examples of how to make a GET, PUT and DELETE request readme.

The README.md file of user-manager is [here](https://github.com/keploy/samples-java/pull/55/files#diff-62a07aa720c3b5ed8806a971df294f4cc79272fbf464a020cf3446936246ca10). It already contains GET and PUT calls. I will add the update and delete api calls later. 😃

**Comment by IllTamer** [comment]
Content supplement completed 😜

**Comment by nehagup** [comment]
@IllTamer can you please resolve the conflicts and I shall merge this

**Comment by IllTamer** [comment]
> @IllTamer can you please resolve the conflicts and I shall merge this

Thanks for the reminder, I have resolved the conflict 😝

**Review by nehagup — APPROVED** [review]

**Pull request merged**
