### PR TITLE
Added samples of Google Map SDK

### PR DESCRIPTION
**Pull request by mrjayrai**
Pull Request for Google Map SDK

## Description

In this pull request , I have made Google Map SDK as a multi module project according to the Keploy SDK.

## Type of change

Please delete options that are not relevant.

- [ ] New feature (non-breaking change which adds functionality)

...

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] My changes generate no new warnings
- [x] Any dependent changes have been merged and published in downstream modules
- [ ] I have checked my code and corrected any misspellings
- [x] I have tagged the reviewers in a comment below incase my pull request is ready for a review
- [x] I have signed the commit message to agree to Developer Certificate of Origin (DCO) (to certify that you wrote or otherwise have the right to submit your contribution to the project.) by adding "--signoff" to my git commit command.

### CODE REVIEW

**Comment by Sarthak160** [comment]
Hey @mrjayrai  `samples-googlemap` is not opening .

**Comment by mrjayrai** [comment]
Ok sir give me a cup of time I'll fix it

**Comment by mrjayrai** [comment]
Hello, @Sarthak160 now you can access the folder

**Comment by Sarthak160** [comment]
This is not a REST API @mrjayrai . Keploy generates test cases by making API calls .

**Pull request closed without merging**
