### PR TITLE
Feat: Add springboot-mongodb app.

### PR DESCRIPTION
**Pull request by IllTamer**
# Pull Request Template

## Description

Closes: https://github.com/keploy/keploy/issues/913
Closes: https://github.com/keploy/keploy/issues/1142

## Type of change

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

## Additional Context (Please include any Screenshots/gifs if relevant)

- Changed project structure.

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [x] Any dependent changes have been merged and published in downstream modules
- [x] I have checked my code and corrected any misspellings
- [x] I have tagged the reviewers in a comment below incase my pull request is ready for a review
- [x] I have signed the commit message to agree to Developer Certificate of Origin (DCO) (to certify that you wrote or otherwise have the right to submit your contribution to the project.) by adding "--signoff" to my git commit command.

### CODE REVIEW

**Comment by Shashwat79802** [comment]
> I have changed the project structure and you can start over with workflow approval please if you are free. @Shashwat79802 : )

The build check is still failing, we need to reconfigure the build check a bit to do the build check in the subdirectories instead of doing in the parent dir itself.

**Comment by IllTamer** [comment]
> > I have changed the project structure and you can start over with workflow approval please if you are free. @Shashwat79802 : )
> 
> The build check is still failing, we need to reconfigure the build check a bit to do the build check in the subdirectories instead of doing in the parent dir itself.

Yes, I noticed that the workflow is compiled in the root directory of the project, but there is no maven file there. I will modify the workflow and submit it after the local test is completed.  Thank you for your suggestion 😃

**Comment by IllTamer** [comment]
As the result, I chose a directory structure like this instead of the one originally submitted.
```linux
└── samples-java
    ├── pom.xml
    ├── springboot-jpa
    └── springboot-mongodb
```
Origin:
```linux
└─ samples-java
   ├── Contributing
   └── samples-java
       ├── pom.xml
       ├── springboot-jpa
       └── springboot-mongodb
```
I think this hierarchical distribution can make the project structure clearer, and based on the design of parent-child modules, when the pom file of samples-java is moved to the top level, mvn can directly find the pom file of the project when executing the workflow.

**Comment by IllTamer** [comment]
As the result, I chose a directory structure like this instead of the one originally submitted.
```linux
└── samples-java
    ├── pom.xml
    ├── springboot-jpa
    └── springboot-mongodb
```
Origin:
```linux
└─ samples-java
   ├── Contributing
   └── samples-java
       ├── pom.xml
       ├── springboot-jpa
       └── springboot-mongodb
```
I think this hierarchical distribution can make the project structure clearer, and based on the design of parent-child modules, when the pom file of samples-java is moved to the top level, mvn can directly find the pom file of the project when executing the workflow.

**Comment by Shashwat79802** [comment]
> As the result, I chose a directory structure like this instead of the one originally submitted.
> 
> ```
> └── samples-java
>     ├── Contributing
>     ├── pom.xml
>     ├── springboot-jpa
>     └── springboot-mongodb
> ```
> 
> Origin:
> 
> ```
> └─ samples-java
>    ├── Contributing
>    └── samples-java
>        ├── pom.xml
>        ├── springboot-jpa
>        └── springboot-mongodb
> ```
> 
> I think this hierarchical distribution can make the project structure clearer, and based on the design of parent-child modules, when the pom file of samples-java is moved to the top level, mvn can directly find the pom file of the project when executing the workflow.

There's no README.md file associated with the application you're contributing. You've just added the README.md of the SQL app to your app.

**Comment by IllTamer** [comment]
> There's no README.md file associated with the application you're contributing. You've just added the README.md of the SQL app to your app.

The README.md file of the project is stored in each sample (Such as `samples-java/springboot-mongodb/README.md`). This is the README.md link [click](https://github.com/keploy/samples-java/pull/53/files#diff-bf44098fd9da556d8ab55daede568ad3f3bbf685314fbe8c5ee0511bfe0ef153) of springboot-mongodb. I copied and modified the README.md file in the `original` project.

**Comment by Shashwat79802** [comment]
The issue has been resolved with the merge of the PR - https://github.com/keploy/samples-java/pull/54

**Pull request closed without merging**
