### PR TITLE
Issue 955

### PR DESCRIPTION
**Pull request by Bhanuteja01**
# Pull Request Template

## Description

Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.

Fixes # 955

## Type of change

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
-  [x] This change requires a documentation update

## How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

## Additional Context (Please include any Screenshots/gifs if relevant)

...

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules
- [ ] I have checked my code and corrected any misspellings
- [ ] I have tagged the reviewers in a comment below incase my pull request is ready for a review
- [ ] I have signed the commit message to agree to Developer Certificate of Origin (DCO) (to certify that you wrote or otherwise have the right to submit your contribution to the project.) by adding "--signoff" to my git commit command.

### CODE REVIEW

**Comment by Sarthak160** [comment]
Please Update the README.md as well !!

**Comment by Sarthak160** [comment]
Also Have you did `mvn clean install` , locally ?? As build is failing !!

**Comment by Sarthak160** [comment]
> @Sarthak160 Changes i did is correct??

Remove the keploy-sdk pom instead of commenting and also remove the already created testcases from the src/test folder.

**Comment by Bhanuteja01** [comment]
@Sarthak160 should i delete entire SamplesJavaApplication_Test.java file

**Comment by Sarthak160** [comment]
> @Sarthak160 should i delete entire SamplesJavaApplication_Test.java file

Yes , you can remove the JunitTestFile for now .

**Review by Bhanuteja01 — COMMENTED** [review]
Is it ok

**Comment by Sarthak160** [comment]
> I have doubt in update readme

Whats your doubt ??

**Comment by Bhanuteja01** [comment]
how to change the readme file

**Comment by Sonichigo** [comment]
The issue attached to this PR has been resolved

**Pull request closed without merging**
